# Polkadot
- symbol: dot
  geckoid: polkadot
  contract: polkadot
# Astar
- symbol: astr
  geckoid: astar
  contract: astar
# Moonbeam
- symbol: glmr
  geckoid: moonbeam
  contract: moonbeam
# Well (sample ERC20 token over MoonBeam network)
- symbol: well
  geckoid: moonwell-artemis
  contract: moonbeam
